CREATE TABLE IF NOT EXISTS {tablename}
(
"OrganizationIdentifier" character varying,
"OrganizationFormalName" character varying,
"ActivityIdentifier" character varying,
"ActivityTypeCode" character varying,
"ActivityMediaName" character varying,
"ActivityMediaSubdivisionName" character varying,
"ActivityStartDate" timestamp with time zone,
"ActivityStartTime_Time" character varying,
"ActivityStartTime_TimeZoneCode" character varying,
"ActivityEndDate" timestamp with time zone,
"ActivityEndTime_Time" character varying,
"ActivityEndTime_TimeZoneCode" character varying,
"ActivityDepthHeightMeasure_MeasureValue" float,
"ActivityDepthHeightMeasure_MeasureUnitCode" character varying,
"ActivityDepthAltitudeReferencePointText" character varying,
"ActivityTopDepthHeightMeasure_MeasureValue" character varying,
"ActivityTopDepthHeightMeasure_MeasureUnitCode" character varying,
"ActivityBottomDepthHeightMeasure_MeasureValue" character varying,
"ActivityBottomDepthHeightMeasure_MeasureUnitCode" character varying,
"ProjectIdentifier" character varying,
"ActivityConductingOrganizationText" character varying,
"MonitoringLocationIdentifier" character varying,
"ActivityCommentText" character varying,
"SampleAquifer" character varying,
"HydrologicCondition" character varying,
"HydrologicEvent" character varying,
"SampleCollectionMethod_MethodIdentifier" character varying,
"SampleCollectionMethod_MethodIdentifierContext" character varying,
"SampleCollectionMethod_MethodName" character varying,
"SampleCollectionEquipmentName" character varying,
"ResultDetectionConditionText" character varying,
"CharacteristicName" character varying,
"ResultSampleFractionText" character varying,
"ResultMeasureValue" float,
"ResultMeasure_MeasureUnitCode" character varying,
"MeasureQualifierCode" character varying,
"ResultStatusIdentifier" character varying,
"StatisticalBaseCode" character varying,
"ResultValueTypeName" character varying,
"ResultWeightBasisText" character varying,
"ResultTimeBasisText" character varying,
"ResultTemperatureBasisText" character varying,
"ResultParticleSizeBasisText" character varying,
"PrecisionValue" character varying,
"ResultCommentText" character varying,
"USGSPCode" character varying,
"ResultDepthHeightMeasure_MeasureValue" float,
"ResultDepthHeightMeasure_MeasureUnitCode" character varying,
"ResultDepthAltitudeReferencePointText" character varying,
"SubjectTaxonomicName" character varying,
"SampleTissueAnatomyName" character varying,
"ResultAnalyticalMethod_MethodIdentifier" character varying,
"ResultAnalyticalMethod_MethodIdentifierContext" character varying,
"ResultAnalyticalMethod_MethodName" character varying,
"MethodDescriptionText" character varying,
"LaboratoryName" character varying,
"AnalysisStartDate" character varying,
"ResultLaboratoryCommentText" character varying,
"DetectionQuantitationLimitTypeName" character varying,
"DetectionQuantitationLimitMeasure_MeasureValue" character varying,
"DetectionQuantitationLimitMeasure_MeasureUnitCode" character varying,
"PreparationStartDate" character varying,
"ProviderName" character varying,
CONSTRAINT wqp_{tablename}_pkey PRIMARY KEY ("ActivityIdentifier")
)